version: "3.7"
services:
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: siscustomers
      MYSQL_USER: "customersapi"
      MYSQL_PASSWORD: "nE5kMc7JCGNqwDQN"
      MYSQL_ROOT_PASSWORD: "nE5kMc7JCGNqwDQN"