version: "3.7"
services:
  springboot-customers-api:
    image: customers-api:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/customers-api
    ports:
      - "8081:8081"
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: siscustomers
      MYSQL_USER: "customersapi"
      MYSQL_PASSWORD: "nE5kMc7JCGNqwDQN"
      MYSQL_ROOT_PASSWORD: "nE5kMc7JCGNqwDQN"