version: "3.7"
services:
  customers_api:
    image: customers-api:1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
    environment:
      SPRING_DATASOURCE: mysql_db
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: siscustomers
      MYSQL_USER: customersapi
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQN
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN