spring:
  application:
    name: customers-api
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/data/customer
    username: customers
    password: customers
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    validate-on-migrate: true