server:
  servlet:
    context-path: /customers
spring:
  application:
    name: customers-api
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customers
    username: customers
    password: customers
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      max-lifetime: 150000
      pool-name: customers
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: America/Sao_Paulo
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
  flyway:
    enabled: true
    validate-on-migrate: true
    validateMigrationNaming: true