spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: America/Sao_Paulo
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    validate-on-migrate: false
    validateMigrationNaming: true